version: '3.4'

services:
  pets_fastapi:
    image: pets_fastapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 3000"
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
  db:
    image: postgres:13-alpine
    volumes:
      - fastapi_pets_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_pets_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  fastapi_pets_data:
