"""pet table extended

Revision ID: a88f121dce96
Revises: 7388e2b471ee
Create Date: 2023-04-25 08:17:49.962242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from db.database import Base
from api.pets.models import PetTypesColumn
# revision identifiers, used by Alembic.
revision = 'a88f121dce96'
down_revision = '7388e2b471ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    PetTypesColumn.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pet', sa.Column('type',
                                   postgresql.ENUM('dog', 'cat', name='type',
                                                   metadata=Base.metadata,
                                                   create_constraint=True),
                                   nullable=False))
    op.add_column('Pet', sa.Column('created_at', sa.DateTime(),
                                   nullable=False,
                                   server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pet', 'created_at')
    op.drop_column('Pet', 'type')
    # ### end Alembic commands ###
    PetTypesColumn.drop(op.get_bind(), checkfirst=True)
